### ISSUE TITLE
possibility of access from internet

### ISSUE THREAD

**Issue by mehrdad987** [G6EJD/ESP32-8266-FIle-Upload#1]
Hi Mr.Dave
good job with your code, hope you have a minute to help me if it's possible to access the page from the internet 
I wrote a code that stores the information of several different sensors and devices in memory
I wanted to know if I could access the SDcard from the internet

**Comment by G6EJD** [comment]
Yes, you need to add a rule to your Router that forwards a connection request to your ESP server.
Example your ESP server address is 192.168.0.55
Now make a rule that forwards an external connection request to your ESP server
Rule
Port:80 192.168.0.55 TCP/UDP

Now a connection to your Internet IP e.g. www.mysite.com or external IP will be directed to the ESP server and it works from anywhere in the world. You need to check that your router allows port forwarding, not all do.

**Comment by mehrdad987** [comment]
thank you

Do I need to make some changes to the code?
I just searched for forwarding and found some details but Until now I could not access the ESP
is there any completed project?

**Comment by G6EJD** [comment]
There are no code changes required when you have set a port forwarding rule you can connect to the ESP from the internet, you will need a domain name or find your internet IP address and then connect to that, the router will then transfer the connection to the ESP, it’s not an ESP code issue all in your router, so you won’t find s complete solution as there are so many routers on the market it would be impossible to cover them all.
