### ISSUE TITLE
( ESP 12 E  )FILE GETTING MODIFIED DURING HTTP POST

### ISSUE THREAD

**Issue by rohank27696** [G6EJD/ESP32-8266-FIle-Upload#2]
I am trying to upload a file in esp using HTTP post. but when I try to upload the content in the file gets changed.
below I have attached the code. please use esp 8266 sketch uploader to load upload.html file. i have attached the file to be uploaded : Print1.txt . In this file there is eight byte data ( capturelog2 image)  , but when I upload it to esp it shows 16 byte ( capturelog1 image) .
[PROJ_1.zip](https://github.com/G6EJD/ESP32-8266-File-Upload/files/6317044/PROJ_1.zip)

**Comment by G6EJD** [comment]
Have you tried a simple text file file, does that work?
What file format are you trying to upload, file properties?
Is the size different by 1 byte or many bytes?
What size is the file?
What version of the IDE and ES8266 compiler are you using?
This is probably a problem with the HTTP library not this code?

**Comment by rohank27696** [comment]
yes i have tried simple text it works.
i have problem only when I use extended ascii (128 -255) in the file.
I have used Arduino ide.
in file I have wrote 8 bytes of 0xFF .
size of file 16 bytes.

**Comment by G6EJD** [comment]
The important aspect is to check file sizes.
I checked the http library and there is nothing in the code that modifies the bytes being transferred so this is most likely how the file is then being read and interpreted by the browser if html do you have a Lang and char set directive in your html?

**Comment by rohank27696** [comment]
Lang : en
charset : utf-8

**Comment by G6EJD** [comment]
File size difference?
Have you looked at the copied file content?

**Comment by rohank27696** [comment]
file size is same.
but the contents are changed in the file . the original data is getting converted into utf-8 encoding
Suppose I sent:
ASCII: ÿÿÿÿ
hex :FFFFFFFF

after uploading:-
ASCII: Ã¿Ã¿Ã¿Ã¿
hex: c3 bf c3 bf c3 bf c3 bf

https://www.rapidtables.com/convert/number/ascii-to-hex.html

![utfencoding](https://user-images.githubusercontent.com/67577232/114982000-789c3a00-9eac-11eb-95f3-315061204503.JPG)

**Comment by G6EJD** [comment]
I can't explain what's happening, I have looked at the webserver source code and can see no mechanism that changes the byte contents, it uses a file.write function, there is no file manipulation and binary files are transferred OK. So this must be down to the browser or the webserver serving out the pages of HTML. Given that HTML is a text file [0..127] are you using some special characters? But HTML is not designed to do that.
It would help me if I could understand what your trying to transfer and use the files for. I have never had any problems with any of my webservers.

BTW watch out at 18:00 today, I'm releasing an Asynchwebserver example for file upload/download, etc.

**Comment by rohank27696** [comment]
Yes, I am using ASCII [0..127] and extended ascii[128..255].
I am transferring bit format of an image to esp12 e  and storing it in file and then sending the bytes thru serial for printing.
 
i have attached the file below I am trying to send
[bitformat.txt.txt](https://github.com/G6EJD/ESP32-8266-File-Upload/files/6324173/bitformat.txt.txt)

**Comment by G6EJD** [comment]
It's binary/image file, but nonetheless there is no other way of uploading the file, it is already being transferred as a binary. This looks like a webserver issue.

**Comment by rohank27696** [comment]
I am using the google chrome browser for uploading files. Is there any setting change required? also can you suggest another way to upload a file without  using chrome browser .

**Comment by G6EJD** [comment]
There are no browser settings that tell the browser to upload in binary, it comes from the form and query that is sent, here's the line in the code for the ESP that does that:
  webpage += F("<FORM action='/fupload' method='post' enctype='multipart/form-data'>");

And it is correctly formatted to ask for a 'multipart/form-data' response from the browser, so maybe try another browser like Firefox
